# Generated by Django 4.2 on 2025-03-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='learning_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='today_words',
            field=models.IntegerField(default=20, verbose_name='今日学习单词数'),
        ),
    ]
