# Generated by Django 4.2 on 2025-03-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usermodel_learning_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='today_words',
            field=models.IntegerField(default=0, verbose_name='今日学习单词数'),
        ),
    ]
