# Generated by Django 4.2 on 2025-03-09 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usermodel_today_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='using_word_band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userwordbandmodel'),
        ),
        migrations.AlterField(
            model_name='userwordbandmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_bands', to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
    ]
