# Generated by Django 4.2 on 2025-03-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_usermodel_learning_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwordbandmodel',
            name='today_studied',
            field=models.IntegerField(default=0, verbose_name='今日学习数'),
        ),
    ]
