# Generated by Django 4.2 on 2025-03-09 22:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_dailyrecordmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errorwordmodel',
            name='last_error_time',
        ),
        migrations.AddField(
            model_name='errorwordmodel',
            name='correct_threshold',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='errorwordmodel',
            name='next_review',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='errorwordmodel',
            name='track_correct_count',
            field=models.IntegerField(default=0),
        ),
    ]
