# Generated by Django 4.2 on 2025-03-09 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_errorwordmodel_last_error_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorwordmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_words', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
