# Generated by Django 4.2 on 2025-03-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'ordering': ['order_number', 'id'], 'verbose_name': '词书类别表', 'verbose_name_plural': '词书类别表'},
        ),
        migrations.RenameField(
            model_name='wordmodel',
            old_name='word',
            new_name='spelling',
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='order_number',
            field=models.IntegerField(default=10, verbose_name='排序字段'),
        ),
        migrations.AddField(
            model_name='wordmodel',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wordmodel',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wordmodel',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
