# Generated by Django 4.2 on 2025-03-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_alter_wordmodel_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordmodel',
            name='spelling',
            field=models.CharField(max_length=100, verbose_name='单词'),
        ),
    ]
