# Generated by Django 4.2 on 2025-03-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_alter_wordmodel_spelling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordmodel',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='wordmodel',
            name='status',
        ),
        migrations.AlterField(
            model_name='wordmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
