# Generated by Django 4.2 on 2025-03-09 14:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_usermodel_using_word_band_and_more'),
        ('words', '0005_remove_wordmodel_frequency_remove_wordmodel_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WordBankModel',
            new_name='WordBandModel',
        ),
    ]
