# Generated by Django 4.2 on 2025-03-09 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0006_rename_wordbankmodel_wordbandmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandtowordmodel',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='words.wordmodel', verbose_name='对应单词'),
        ),
        migrations.AlterField(
            model_name='wordbandmodel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='词书名称'),
        ),
    ]
